### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by RuinChristmas** [EvanK/ubuntu-purge-kernels#3]
Hi Evan,
I am desperate to make space on my boot partition (0 Bytes free of 500 MB).  I am running Linux Mint 17.1  I tried to remove kernels according to stackexchange posts and it shows that I only have one left

```
ruin@tiger /boot $ uname -r
3.13.0-98-generic
```

There doesn't look to be anywhere near 500 MB of files in /boot.  So I tried your program but got this error.  

```
ruin@tiger ~ $ python purge-kernels.py
  File "purge-kernels.py", line 5
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```
Thanks for any help,

Ruin

**Comment by EvanK** [comment]
Sorry I never saw this issue (lost in the torrent of my inbox).

My script doesn't contain any html (certainly not a doctype), so you may have grabbed the github html page _around_ the script? Try this instead:

```bash
# fetch the raw script (and put it in home dir, for example sake)
wget -O $HOME/purge-kernels.py https://raw.githubusercontent.com/EvanK/ubuntu-purge-kernels/master/purge-kernels.py
# and then run it
python $HOME/purge-kernels.py
```
